CREATE TABLE "ai_architecture_diagnostic_applications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_name" text NOT NULL,
	"email" text NOT NULL,
	"industry" text,
	"org_size" text,
	"contact_title" text,
	"score" integer NOT NULL,
	"priority" text,
	"recommended_path" text NOT NULL,
	"reasoning" text,
	"use_case" text NOT NULL,
	"ai_scope" text,
	"users" text,
	"systems" text,
	"infrastructure" text,
	"architecture_maturity" text,
	"regulatory" text,
	"pii_level" text,
	"engineering_team" text,
	"ai_experience" text,
	"budget_range" text NOT NULL,
	"timeline" text,
	"status" text DEFAULT 'new',
	"created_at" timestamp DEFAULT now()
);
