import type { Scenario } from './schemas';

export const scenarios: Scenario[] = [
  {
    id: 'billing-refund',
    title: 'Billing Dispute & Refund',
    description: 'Customer disputes a charge and requests a refund. Transfers from orchestrator to billing.',
    type: 'orchestrator',
    category: 'Billing',
    steps: [
      { speaker: 'system', text: 'Call connected — Orchestrator Agent active', delay: 300 },
      { speaker: 'agent', text: 'Thank you for calling customer support. My name is Alex, how can I help you today?', delay: 800 },
      { speaker: 'caller', text: "Hi, I was charged $49.99 on my last statement and I didn't authorize that purchase.", delay: 2000 },
      { speaker: 'agent', text: "I understand your concern about the unauthorized charge. Let me look into that for you. I'll connect you with our billing specialist who can resolve this.", delay: 1500 },
      { speaker: 'system', text: 'Transferred to Billing Agent', delay: 500, action: 'transfer', transferTo: 'billing' },
      { speaker: 'agent', text: "Hello, this is Jordan from billing. I can see the charge on your account. Let me pull up the transaction details.", delay: 1200, agentType: 'billing' },
      { speaker: 'caller', text: "Yes, it showed up three days ago. I haven't made any purchases from your platform recently.", delay: 2000 },
      { speaker: 'agent', text: "I've reviewed the transaction and I can confirm this was a duplicate charge from a system error. I'm initiating a full refund of $49.99 right now.", delay: 1800, agentType: 'billing' },
      { speaker: 'system', text: 'Refund processed — $49.99', delay: 400 },
      { speaker: 'agent', text: "The refund has been processed and should appear in your account within 3 to 5 business days. Is there anything else I can help with?", delay: 1200, agentType: 'billing' },
      { speaker: 'caller', text: "No, that's perfect. Thank you for the quick resolution.", delay: 1500 },
      { speaker: 'agent', text: "You're welcome! Thank you for your patience. Have a great day.", delay: 800, agentType: 'billing' },
      { speaker: 'system', text: 'Call ended — Duration: 2m 15s', delay: 500 },
    ],
  },
  {
    id: 'tech-outage',
    title: 'Service Outage Report',
    description: 'Customer reports inability to access account. Escalated to technical with barge-in.',
    type: 'orchestrator',
    category: 'Technical',
    steps: [
      { speaker: 'system', text: 'Call connected — Orchestrator Agent active', delay: 300 },
      { speaker: 'agent', text: "Welcome to support. I'm here to help. What seems to be the issue?", delay: 800 },
      { speaker: 'caller', text: "I can't log into my account! I've been trying for the past hour. This is completely unacceptable.", delay: 1800 },
      { speaker: 'agent', text: "I apologize for the inconvenience. Let me check our systems—", delay: 800 },
      { speaker: 'caller', text: "I need this fixed NOW. I have a deadline in 30 minutes!", delay: 600, action: 'barge-in' },
      { speaker: 'system', text: 'Barge-in detected — Interruption handled', delay: 200 },
      { speaker: 'agent', text: "I completely understand the urgency. I'm transferring you to our technical team right now for immediate assistance.", delay: 1000 },
      { speaker: 'system', text: 'Transferred to Technical Agent', delay: 500, action: 'transfer', transferTo: 'technical' },
      { speaker: 'agent', text: "Hi, this is Sam from technical support. I can see there's a regional service disruption affecting your area. Let me apply a workaround.", delay: 1500, agentType: 'technical' },
      { speaker: 'system', text: 'VAD: Noise cancellation active', delay: 300, action: 'noise-cancel' },
      { speaker: 'agent', text: "I've rerouted your connection through our backup servers. Could you try logging in now?", delay: 1200, agentType: 'technical' },
      { speaker: 'caller', text: "Let me try... Yes! I'm in! Thank you so much.", delay: 2500 },
      { speaker: 'agent', text: "Excellent! The disruption should be fully resolved within the next 30 minutes. Your session is now locked in on the backup server so you won't be interrupted.", delay: 1500, agentType: 'technical' },
      { speaker: 'system', text: 'Lock-in active — Session secured', delay: 300, action: 'lock-in' },
      { speaker: 'caller', text: "Perfect, thank you for the fast help!", delay: 1000 },
      { speaker: 'system', text: 'Call ended — Duration: 3m 42s', delay: 500 },
    ],
  },
  {
    id: 'retention-cancel',
    title: 'Subscription Cancellation Save',
    description: 'Customer wants to cancel. Multi-transfer through billing then retention with lock-in.',
    type: 'orchestrator',
    category: 'Retention',
    steps: [
      { speaker: 'system', text: 'Call connected — Orchestrator Agent active', delay: 300 },
      { speaker: 'agent', text: "Thank you for calling. How may I assist you today?", delay: 800 },
      { speaker: 'caller', text: "I want to cancel my subscription. I'm paying too much for what I'm getting.", delay: 1800 },
      { speaker: 'agent', text: "I'm sorry to hear that. Before we proceed, let me connect you with a specialist who might be able to find a better plan for you.", delay: 1200 },
      { speaker: 'system', text: 'Transferred to Billing Agent', delay: 500, action: 'transfer', transferTo: 'billing' },
      { speaker: 'agent', text: "Hello, I see you're on our Premium plan at $29.99 per month. Let me review your usage patterns to see if there's a more suitable option.", delay: 1500, agentType: 'billing' },
      { speaker: 'caller', text: "I barely use half the features. It's just not worth it anymore.", delay: 1500 },
      { speaker: 'agent', text: "I understand. Based on your usage, I'd like to transfer you to our retention team who can offer you a personalized plan.", delay: 1200, agentType: 'billing' },
      { speaker: 'system', text: 'Transferred to Retention Agent', delay: 500, action: 'transfer', transferTo: 'retention' },
      { speaker: 'agent', text: "Hi there, I'm Morgan from customer success. I've reviewed your account and I'd like to offer you our Essential plan at $14.99 per month — that's 50% off with all the features you actually use.", delay: 2000, agentType: 'retention' },
      { speaker: 'caller', text: "Hmm, that's actually a pretty good deal. What's included?", delay: 1500 },
      { speaker: 'agent', text: "You'll keep unlimited storage, API access, and priority support. The only change is removing the enterprise collaboration features you haven't been using.", delay: 1800, agentType: 'retention' },
      { speaker: 'system', text: 'Lock-in active — Retention offer secured', delay: 300, action: 'lock-in' },
      { speaker: 'caller', text: "OK, let's do that. Switch me to the Essential plan.", delay: 1200 },
      { speaker: 'agent', text: "Done! Your new plan is active immediately. You'll see the adjusted billing on your next statement. Thank you for staying with us!", delay: 1500, agentType: 'retention' },
      { speaker: 'system', text: 'Plan changed: Premium → Essential — Saved: $15/mo', delay: 400 },
      { speaker: 'system', text: 'Call ended — Duration: 4m 08s', delay: 500 },
    ],
  },
  {
    id: 'tech-multi-transfer',
    title: 'Complex Multi-Agent Resolution',
    description: 'Technical issue requiring billing verification first, then technical fix, with barge-in and VAD.',
    type: 'orchestrator',
    category: 'Technical',
    steps: [
      { speaker: 'system', text: 'Call connected — Orchestrator Agent active', delay: 300 },
      { speaker: 'agent', text: "Good afternoon, you've reached our support center. How can I help?", delay: 800 },
      { speaker: 'caller', text: "My API keys stopped working and I'm getting 403 errors on all my endpoints.", delay: 1800 },
      { speaker: 'agent', text: "That sounds like it could be an account or billing issue. Let me verify your account status first.", delay: 1000 },
      { speaker: 'system', text: 'Transferred to Billing Agent', delay: 500, action: 'transfer', transferTo: 'billing' },
      { speaker: 'agent', text: "I can see your account is active but there was a failed payment attempt yesterday. Let me reprocess that.", delay: 1500, agentType: 'billing' },
      { speaker: 'system', text: 'Payment reprocessed successfully', delay: 400 },
      { speaker: 'agent', text: "Payment is confirmed. However, the API keys may need to be regenerated. Let me transfer you to our technical team.", delay: 1200, agentType: 'billing' },
      { speaker: 'system', text: 'Transferred to Technical Agent', delay: 500, action: 'transfer', transferTo: 'technical' },
      { speaker: 'system', text: 'VAD: Background noise detected — Noise cancellation engaged', delay: 300, action: 'noise-cancel' },
      { speaker: 'agent', text: "I see the billing issue has been resolved. I'm regenerating your API keys now. This will take just a moment.", delay: 1500, agentType: 'technical' },
      { speaker: 'caller', text: "Wait, will this break my existing integrations—", delay: 800, action: 'barge-in' },
      { speaker: 'system', text: 'Barge-in detected — Agent paused', delay: 200 },
      { speaker: 'agent', text: "Great question. Your existing integrations will continue to work. The new keys will have a 24-hour overlap period where both old and new keys are valid.", delay: 1800, agentType: 'technical' },
      { speaker: 'system', text: 'New API keys generated — Overlap period: 24h', delay: 400 },
      { speaker: 'agent', text: "Your new keys have been sent to your registered email. Is there anything else you need help with?", delay: 1200, agentType: 'technical' },
      { speaker: 'caller', text: "No, that covers everything. Thanks for the thorough help!", delay: 1200 },
      { speaker: 'system', text: 'Call ended — Duration: 5m 22s', delay: 500 },
    ],
  },
];
